export const routes = {
  welcome: '/',
  login: '/login',
  resetPassword: '/reset-password',
  loginSuccess: '/login-success',
  onboardingStart: '/onboarding/start',
  onboardingBasic: '/onboarding/basic-info',
  onboardingGoalCollect: '/onboarding/training-goal',
  onboardingBaseCollect: '/onboarding/training-base',
  onboardingWorkStatus: '/onboarding/work-status',
  onboardingSummary: '/onboarding/profile-summary',
  onboarding: '/onboarding',
  planLoading: '/plan-loading',
  planPreview: '/plan-preview',
  app: {
    home: '/app/home',
    training: '/app/training',
    nutrition: '/app/nutrition',
    profile: '/app/profile',
    community: '/app/community',
    workout: '/app/workout',
    planNew: '/app/plans/new',
    planStructure: '/app/plans/structure',
    planAddExercise: '/app/plans/add-exercise',
    planEditDay: '/app/plans/edit-day',
    tdeeDashboard: '/app/profile/tdee',
    fitnessChat: '/app/training/ai-chat',
    fitnessAnalysis: '/app/training/ai-analysis',
    fitnessResult: '/app/training/ai-result',
    supportedActions: '/app/exercise/supported',
    exerciseDetail: '/app/exercise/detail/:slug',
    exerciseDetailLat: '/app/exercise/detail/lat-pulldown',
    exercise: '/app/exercise',
    live: '/app/live',
    equipmentResult: '/app/equipment/result',
    manualEquipment: '/app/equipment/manual',
    feedback: '/app/feedback',
    summary: '/app/summary',
    assessment: '/app/assessment',
    mealCapture: '/app/meal-capture',
    mealConfirm: '/app/meal-confirm',
    nutritionChat: '/app/nutrition/chat',
    nutritionRecommend: '/app/nutrition/recommend',
    notifications: '/app/notifications',
    profileAccount: '/app/profile/account',
    profileSupport: '/app/profile/support',
    personalInfo: '/app/profile/personal-info',
    bodyData: '/app/profile/body-data',
    trainingPreferences: '/app/profile/training-preferences',
    privacy: '/app/profile/privacy',
    notificationSettings: '/app/profile/notification-settings',
    help: '/app/profile/help',
    about: '/app/profile/about',
    supportFeedback: '/app/profile/feedback',
    invite: '/app/profile/invite',
    buddyMatch: '/app/community/buddy-match',
    chatDraft: '/app/community/chat-draft',
  },
} as const

export const tabRoutes = [routes.app.training, routes.app.community, routes.app.nutrition, routes.app.profile] as const

export type AppRoute = (typeof routes)[keyof typeof routes] | (typeof routes.app)[keyof typeof routes.app]
